import { useMemo } from 'react';
import type { BodyMeasurements, BilateralMeasurement } from '../types/measurements';
import maleVolume from '../assets/silhouette_volume_male.png';
import femaleVolume from '../assets/silhouette_volume_female.png';

interface Props {
    currentMeasurements?: BodyMeasurements;
    referenceMeasurements?: BodyMeasurements;
    sex?: 'male' | 'female';
    onMarkerClick?: (zone: string) => void;
}

// Helper to get value from bilateral or number
const getVal = (m: number | BilateralMeasurement | undefined, side?: 'left' | 'right'): number => {
    if (m === undefined) return 0;
    if (typeof m === 'number') return m;
    if (side && m[side] > 0) return m[side];
    return (m.left + m.right) / 2;
};

// Color Logic
const getZoneColor = (current: number, reference: number) => {
    if (!current || !reference) return 'transparent';

    const ratio = current / reference;

    if (ratio < 0.97) return 'rgba(59, 130, 246, 0.6)'; // Blue (Loss)
    if (ratio >= 0.97 && ratio <= 1.03) return 'rgba(107, 114, 128, 0.4)'; // Gray (Stable)
    if (ratio > 1.03 && ratio <= 1.08) return 'rgba(234, 179, 8, 0.5)'; // Yellow (Moderate Growth)
    return 'rgba(239, 68, 68, 0.5)'; // Red (Significant Growth)
};

export const VolumeHeatmap = ({ currentMeasurements, referenceMeasurements, sex = 'male', onMarkerClick }: Props) => {
    const silhouetteImg = sex === 'female' ? femaleVolume : maleVolume;

    // Paths generated by poly_generator.py from detailed silhouette analysis
    const MALE_PATHS = {
        neck: "M 76.8,66.0 76.8,74.0 76.2,74.7 76.2,77.3 72.8,82.0 69.5,84.7 69.5,98.7 129.8,98.7 129.8,86.7 119.2,82.0 117.9,80.7 113.2,78.7 111.9,77.3 111.9,76.7 113.9,74.7 120.5,74.7 123.2,72.7 124.5,66.0 Z",
        pecho: "M 49.7,98.7 49.7,154.0 149.7,154.0 149.7,98.7 Z",
        waist: "M 59.6,154.0 59.6,208.7 137.7,208.7 137.1,202.7 139.7,190.7 139.7,154.0 Z",
        hips: "M 57.0,208.7 56.3,211.3 56.3,227.3 55.0,230.7 55.0,233.3 51.7,247.3 142.4,247.3 142.4,240.7 139.1,226.7 139.1,214.7 137.7,208.7 Z",
        "arm-right": "M 27.2,110.0 24.5,114.7 24.5,116.0 23.2,118.0 22.5,122.7 21.9,123.3 21.9,126.7 21.2,127.3 21.2,145.3 19.2,150.0 19.2,152.0 18.5,152.7 17.9,156.7 17.2,157.3 17.2,159.3 16.6,160.0 16.6,163.3 15.9,164.0 15.9,168.7 15.2,169.3 14.6,176.0 41.7,176.0 42.4,175.3 42.4,174.0 43.0,173.3 43.0,172.0 45.0,167.3 45.0,165.3 46.4,163.3 47.7,158.0 49.0,156.0 49.7,156.7 49.7,110.0 Z",
        "forearm-right": "M 14.6,176.0 13.9,178.7 13.2,179.3 12.6,183.3 11.3,185.3 11.3,187.3 10.6,188.0 10.6,189.3 9.3,192.0 8.6,197.3 7.9,198.0 7.9,201.3 7.3,202.0 7.3,205.3 6.6,206.0 6.6,210.7 6.0,211.3 6.0,216.0 5.3,216.7 5.3,222.7 4.6,223.3 4.6,228.0 4.0,228.7 4.0,230.7 28.5,230.7 32.5,222.7 32.5,221.3 33.1,220.7 33.1,219.3 33.8,218.7 33.8,217.3 34.4,216.7 34.4,215.3 35.8,212.7 36.4,208.0 37.1,207.3 37.1,204.7 37.7,204.0 37.7,199.3 38.4,198.7 38.4,194.0 39.1,193.3 39.1,188.7 39.7,188.0 39.7,184.7 40.4,184.0 40.4,181.3 41.1,180.7 41.7,176.0 Z",
        "thigh-right": "M 51.7,247.3 51.0,255.3 45.7,274.7 43.0,299.3 43.7,329.3 48.3,357.3 90.7,357.3 95.4,319.3 95.4,302.7 94.0,291.3 95.4,289.3 95.4,247.3 Z",
        "calf-right": "M 48.3,357.3 54.3,374.0 56.3,383.3 57.0,401.3 53.6,418.7 53.0,434.0 57.0,454.0 58.3,466.7 58.9,467.3 82.1,467.3 88.1,434.0 88.1,419.3 85.4,404.0 87.4,399.3 90.1,383.3 90.7,357.3 Z",
        "arm-left": "M 149.7,110.0 149.7,170.7 151.0,173.3 151.0,175.3 151.7,176.0 178.8,176.0 178.1,174.7 178.1,172.7 176.8,170.0 176.2,164.0 175.5,163.3 175.5,160.0 174.8,159.3 174.2,152.0 173.5,151.3 172.2,144.0 171.5,143.3 171.5,142.0 169.5,137.3 169.5,132.7 170.2,132.0 170.2,125.3 169.5,124.7 169.5,120.7 168.9,120.0 168.9,118.0 168.2,117.3 166.2,110.0 Z",
        "forearm-left": "M 155.6,176.0 155.6,204.0 156.3,204.7 157.0,208.0 158.3,210.0 158.3,211.3 159.6,213.3 160.3,216.7 164.9,226.0 166.2,227.3 167.5,230.7 189.4,230.7 189.4,228.7 188.7,228.0 188.7,224.7 188.1,224.0 188.1,220.7 187.4,220.0 187.4,216.0 186.8,215.3 186.8,210.7 186.1,210.0 185.4,201.3 184.8,200.7 184.8,195.3 184.1,194.7 184.1,192.0 183.4,191.3 183.4,189.3 182.8,188.7 182.1,184.0 180.8,182.0 180.8,180.7 180.1,180.0 180.1,178.7 178.8,176.0 Z",
        "thigh-left": "M 104.0,247.3 104.0,299.3 110.6,325.3 117.9,345.3 120.5,357.3 160.3,357.3 160.9,327.3 159.6,312.7 153.6,284.0 144.4,258.7 143.0,248.0 142.4,247.3 Z",
        "calf-left": "M 120.5,357.3 122.5,364.0 123.8,374.0 128.5,390.0 133.8,401.3 134.4,430.0 136.4,438.7 141.7,453.3 144.4,466.7 145.0,467.3 166.9,467.3 166.9,454.7 168.9,436.7 168.9,428.0 166.2,412.7 161.6,396.7 159.6,384.0 158.9,364.7 160.3,357.3 Z"
    };

    const FEMALE_PATHS = {
        neck: "M 78.8,71.4 78.8,73.3 78.1,74.0 78.1,75.3 77.4,75.9 76.7,77.8 75.3,79.1 75.3,98.4 124.0,98.4 124.0,84.9 122.6,84.9 121.9,84.3 119.9,83.6 118.5,82.3 116.4,81.7 113.0,78.5 113.0,72.0 113.7,71.4 Z",
        pecho: "M 55.5,98.4 55.5,158.2 56.2,158.9 113.0,158.9 113.7,158.2 114.4,158.9 141.1,158.9 142.5,158.2 143.8,156.3 143.8,98.4 Z",
        waist: "M 63.7,158.9 64.4,162.7 71.9,162.7 80.1,160.2 81.5,160.8 77.4,163.4 72.6,164.7 63.7,164.7 63.7,208.4 135.6,208.4 135.6,164.0 124.7,164.7 115.1,160.2 116.4,159.5 119.9,161.5 125.3,162.7 130.8,162.7 135.6,161.5 135.6,158.9 114.4,158.9 113.7,159.5 113.0,158.9 Z",
        hips: "M 55.5,208.4 50.0,220.6 50.0,263.7 150.0,263.7 150.0,227.7 147.9,220.6 142.5,208.4 Z",
        "arm-right": "M 55.5,120.9 24.7,120.9 24.0,122.9 24.0,132.5 23.3,133.2 23.3,140.9 22.6,141.5 21.9,151.8 21.2,152.5 21.2,156.3 20.5,157.0 18.5,169.8 15.8,176.9 15.8,181.4 39.7,181.4 40.4,180.8 41.1,175.0 47.9,152.5 47.9,149.9 47.3,149.2 47.3,138.9 48.6,136.4 49.3,132.5 50.7,130.6 51.4,133.2 49.3,140.2 49.3,148.6 51.4,153.7 55.5,158.2 Z",
        "forearm-right": "M 39.7,181.4 14.4,181.4 13.7,182.7 13.7,184.0 13.0,184.6 13.0,185.9 12.3,186.5 12.3,187.8 11.6,188.5 11.6,190.4 11.0,191.1 11.0,193.0 10.3,193.6 10.3,196.2 9.6,196.8 9.6,236.1 21.9,236.1 22.6,234.8 22.6,233.5 24.7,230.3 24.7,229.0 26.7,225.8 26.7,224.5 28.8,221.3 28.8,220.0 30.1,218.1 30.1,216.8 31.5,214.9 31.5,213.6 32.2,212.9 32.2,211.6 32.9,211.0 32.9,209.7 33.6,209.1 33.6,207.8 34.2,207.1 34.2,205.8 35.6,203.3 35.6,201.3 36.3,200.7 36.3,199.4 37.0,198.8 37.0,196.8 37.7,196.2 37.7,193.0 38.4,192.3 38.4,189.1 39.0,188.5 Z",
        "thigh-right": "M 39.0,263.7 39.7,290.1 49.3,331.9 55.5,353.2 56.8,362.2 56.8,373.7 89.7,373.7 91.1,366.0 91.8,340.9 95.9,315.2 95.9,263.7 Z",
        "calf-right": "M 56.8,373.7 56.8,382.7 54.1,400.8 54.1,418.1 63.7,483.7 82.9,483.7 88.4,427.1 89.0,426.5 89.0,405.9 87.7,400.1 87.0,385.3 89.7,373.7 Z",
        "arm-left": "M 143.8,120.9 143.8,156.3 147.3,149.9 147.3,137.7 145.9,133.8 145.9,131.9 146.6,131.2 148.6,135.1 149.3,140.9 150.0,141.5 150.0,146.7 149.3,147.3 149.3,151.2 148.6,152.5 151.4,160.2 151.4,162.1 154.1,168.5 156.8,181.4 182.2,181.4 180.1,177.5 175.3,162.7 172.6,144.1 171.2,140.2 171.2,135.1 170.5,134.4 170.5,128.7 169.9,128.0 169.9,122.9 169.2,120.9 Z",
        "forearm-left": "M 156.8,181.4 156.8,184.0 157.5,184.6 157.5,188.5 158.2,189.1 158.9,194.9 159.6,195.6 159.6,197.5 160.3,198.1 160.3,199.4 161.0,200.1 161.0,201.3 161.6,202.0 161.6,203.3 162.3,203.9 163.7,209.1 165.1,211.0 165.1,212.3 166.4,214.2 166.4,215.5 167.8,217.4 167.8,218.7 169.9,221.9 169.9,223.2 176.7,236.1 189.7,236.1 189.7,216.1 189.0,215.5 189.0,211.6 188.4,211.0 188.4,206.5 187.7,205.8 187.7,202.0 187.0,201.3 187.0,198.1 186.3,197.5 186.3,194.9 185.6,194.3 185.6,192.3 184.9,191.7 184.9,189.8 184.2,189.1 184.2,187.2 183.6,186.5 182.2,181.4 Z",
        "thigh-left": "M 103.4,263.7 103.4,279.2 104.8,279.8 106.8,297.8 119.2,336.4 125.3,363.5 128.8,373.7 162.3,373.7 161.0,355.7 163.0,331.3 163.0,290.8 159.6,263.7 Z",
        "calf-left": "M 128.8,373.7 133.6,387.3 134.2,418.8 134.9,419.4 135.6,430.4 144.5,470.2 146.6,483.7 163.7,483.7 163.7,381.5 162.3,373.7 Z"
    };

    const zones = useMemo(() => {
        const isFemale = sex === 'female';
        const paths = isFemale ? FEMALE_PATHS : MALE_PATHS;

        return [
            {
                id: 'neck',
                label: 'Cuello',
                path: paths['neck'],
                value: getVal(currentMeasurements?.neck),
                ref: getVal(referenceMeasurements?.neck)
            },
            {
                id: 'pecho',
                label: 'Pecho',
                path: paths['pecho'],
                // Female bust approximate path provided by script or fallback
                value: getVal(currentMeasurements?.pecho),
                ref: getVal(referenceMeasurements?.pecho)
            },
            {
                id: 'waist',
                label: 'Abdomen',
                path: paths['waist'],
                value: getVal(currentMeasurements?.waist),
                ref: getVal(referenceMeasurements?.waist)
            },
            {
                id: 'hips',
                label: 'Cadera',
                path: paths['hips'],
                value: getVal(currentMeasurements?.hips),
                ref: getVal(referenceMeasurements?.hips)
            },
            // Arms
            {
                id: 'arm-left',
                label: 'Bíceps Izq',
                side: 'left',
                path: paths['arm-left'],
                value: getVal(currentMeasurements?.arm, 'left'),
                ref: getVal(referenceMeasurements?.arm, 'left')
            },
            {
                id: 'arm-right',
                label: 'Bíceps Der',
                side: 'right',
                path: paths['arm-right'],
                value: getVal(currentMeasurements?.arm, 'right'),
                ref: getVal(referenceMeasurements?.arm, 'right')
            },
            // Forearms
            {
                id: 'forearm-left',
                label: 'Antebrazo Izq',
                side: 'left',
                path: paths['forearm-left'],
                value: getVal(currentMeasurements?.forearm, 'left'),
                ref: getVal(referenceMeasurements?.forearm, 'left')
            },
            {
                id: 'forearm-right',
                label: 'Antebrazo Der',
                side: 'right',
                path: paths['forearm-right'],
                value: getVal(currentMeasurements?.forearm, 'right'),
                ref: getVal(referenceMeasurements?.forearm, 'right')
            },
            // Thighs
            {
                id: 'thigh-left',
                label: 'Muslo Izq',
                side: 'left',
                path: paths['thigh-left'],
                value: getVal(currentMeasurements?.thigh, 'left'),
                ref: getVal(referenceMeasurements?.thigh, 'left')
            },
            {
                id: 'thigh-right',
                label: 'Muslo Der',
                side: 'right',
                path: paths['thigh-right'],
                value: getVal(currentMeasurements?.thigh, 'right'),
                ref: getVal(referenceMeasurements?.thigh, 'right')
            },
            // Calves
            {
                id: 'calf-left',
                label: 'Gemelo Izq',
                side: 'left',
                path: paths['calf-left'],
                value: getVal(currentMeasurements?.calf, 'left'),
                ref: getVal(referenceMeasurements?.calf, 'left')
            },
            {
                id: 'calf-right',
                label: 'Gemelo Der',
                side: 'right',
                path: paths['calf-right'],
                value: getVal(currentMeasurements?.calf, 'right'),
                ref: getVal(referenceMeasurements?.calf, 'right')
            },
        ];
    }, [currentMeasurements, referenceMeasurements, sex]);

    return (
        <div className="volume-heatmap-container">
            <svg
                viewBox="0 0 200 600"
                className="volume-svg animate-fade-in"
                preserveAspectRatio="xMidYMid meet"
            >
                <defs>
                    <filter id="grayscale">
                        <feColorMatrix type="matrix" values="0.3333 0.3333 0.3333 0 0 0.3333 0.3333 0.3333 0 0 0.3333 0.3333 0.3333 0 0 0 0 0 1 0" />
                    </filter>
                </defs>

                {/* Base Silhouette (Grayscale for better contrast with heatmap) */}
                <image
                    href={silhouetteImg}
                    x="0"
                    y="0"
                    width="200"
                    height="550"
                    style={{
                        opacity: 0.8,
                        filter: 'url(#grayscale)'
                    }}
                />

                {/* Heatmap Layer */}
                <g className="heatmap-overlays" style={{ mixBlendMode: 'multiply' }}>
                    {zones.map((zone) => {
                        const color = getZoneColor(zone.value, zone.ref);
                        return (
                            <path
                                key={zone.id}
                                d={zone.path}
                                fill={color}
                                stroke="transparent"
                                style={{
                                    transition: 'all 0.5s ease',
                                    cursor: onMarkerClick ? 'pointer' : 'default'
                                }}
                                onClick={() => onMarkerClick?.(zone.id)}
                            >
                                <title>{`${zone.label}: ${zone.value}cm (Ref: ${zone.ref}cm)`}</title>
                            </path>
                        )
                    })}
                </g>

                {/* Interactive Hotspots (Invisible but clickable for better UX) */}
                <g className="interaction-layer">
                    {zones.map((zone) => (
                        <path
                            key={`hit-${zone.id}`}
                            d={zone.path}
                            fill="transparent"
                            stroke="rgba(255,255,255,0.1)"
                            strokeWidth="1"
                            className="zone-hitbox"
                            onClick={() => onMarkerClick?.(zone.id)}
                        />
                    ))}
                </g>
            </svg>

            <div className="heatmap-legend">
                <div className="legend-item">
                    <span className="dot" style={{ background: '#3b82f6' }}></span>
                    <span>Pérdida (&#60;99%)</span>
                </div>
                <div className="legend-item">
                    <span className="dot" style={{ background: '#6b7280' }}></span>
                    <span>Estable (±1%)</span>
                </div>
                <div className="legend-item">
                    <span className="dot" style={{ background: '#eab308' }}></span>
                    <span>Crecimiento (1-5%)</span>
                </div>
                <div className="legend-item">
                    <span className="dot" style={{ background: '#ef4444' }}></span>
                    <span>Hipertrofia (&#62;5%)</span>
                </div>
            </div>

            <style>{`
        .volume-heatmap-container {
            position: relative;
            width: 100%;
            height: 100%;
            display: flex;
            flex-direction: column;
            align-items: center;
        }
        .volume-svg {
            height: 100%;
            max-height: 550px;
            filter: drop-shadow(0 0 20px rgba(0,0,0,0.5));
        }
        .zone-hitbox {
            transition: stroke 0.2s;
            cursor: pointer;
        }
        .zone-hitbox:hover {
            stroke: rgba(255,255,255,0.5);
            stroke-width: 2;
        }
        .heatmap-legend {
            margin-top: 1rem;
            display: flex;
            gap: 1rem;
            flex-wrap: wrap;
            justify-content: center;
            background: rgba(0,0,0,0.3);
            padding: 0.5rem 1rem;
            border-radius: 12px;
            border: 1px solid rgba(255,255,255,0.05);
        }
        .legend-item {
            display: flex;
            align-items: center;
            gap: 0.4rem;
            font-size: 0.7rem;
            color: var(--text-secondary);
        }
        .legend-item .dot {
            width: 8px;
            height: 8px;
            border-radius: 50%;
        }
      `}</style>
        </div>
    );
};
