export interface MuscleInfo {
  id: string;
  name: string;
  category: 'core' | 'torso' | 'arms' | 'legs';
  categoryLabel: string;
  isBilateral: boolean;
  instruction: string;
  unit: string;
}

export const MUSCLE_METADATA: Record<string, MuscleInfo> = {
  weight: {
    id: 'weight',
    name: 'Peso Corporal',
    category: 'core',
    categoryLabel: 'Métricas Base',
    isBilateral: false,
    instruction: 'Pésate en ayunas, por la mañana y después de ir al baño.',
    unit: 'kg',
  },
  height: {
    id: 'height',
    name: 'Altura',
    category: 'core',
    categoryLabel: 'Métricas Base',
    isBilateral: false,
    instruction: 'Estatura descalzo con talones juntos y postura erguida.',
    unit: 'cm',
  },
  age: {
    id: 'age',
    name: 'Edad',
    category: 'core',
    categoryLabel: 'Métricas Base',
    isBilateral: false,
    instruction: 'Edad cronológica actual en años cumplidos.',
    unit: 'años',
  },
  bodyFat: {
    id: 'bodyFat',
    name: 'Grasa Corporal',
    category: 'core',
    categoryLabel: 'Métricas Base',
    isBilateral: false,
    instruction: 'Porcentaje de grasa corporal estimado o calculado con fórmula Navy.',
    unit: '%',
  },
  neck: {
    id: 'neck',
    name: 'Cuello',
    category: 'torso',
    categoryLabel: 'Tronco',
    isBilateral: false,
    instruction: 'Pasa la cinta justo por debajo de la nuez de Adán, relajado.',
    unit: 'cm',
  },
  back: {
    id: 'back',
    name: 'Espalda / Hombros',
    category: 'torso',
    categoryLabel: 'Tronco',
    isBilateral: false,
    instruction: 'Circunferencia biacromial máxima rodeando deltoides y dorsal superior.',
    unit: 'cm',
  },
  pecho: {
    id: 'pecho',
    name: 'Pecho (Pectorales)',
    category: 'torso',
    categoryLabel: 'Tronco',
    isBilateral: false,
    instruction: 'Cinta a la altura de los pezones con respiración normal (sin inflar aire).',
    unit: 'cm',
  },
  waist: {
    id: 'waist',
    name: 'Cintura (Abdomen)',
    category: 'torso',
    categoryLabel: 'Tronco',
    isBilateral: false,
    instruction: 'Circunferencia a la altura del ombligo / perímetro más estrecho.',
    unit: 'cm',
  },
  hips: {
    id: 'hips',
    name: 'Cadera (Glúteos)',
    category: 'torso',
    categoryLabel: 'Tronco',
    isBilateral: false,
    instruction: 'Circunferencia máxima alrededor de la mayor prominencia glútea.',
    unit: 'cm',
  },
  arm: {
    id: 'arm',
    name: 'Brazos (Bíceps)',
    category: 'arms',
    categoryLabel: 'Tren Superior',
    isBilateral: true,
    instruction: 'Máxima circunferencia del bíceps en contracción con codo a 90°.',
    unit: 'cm',
  },
  forearm: {
    id: 'forearm',
    name: 'Antebrazos',
    category: 'arms',
    categoryLabel: 'Tren Superior',
    isBilateral: true,
    instruction: 'Perímetro máximo del vientre superior del antebrazo con puño cerrado.',
    unit: 'cm',
  },
  wrist: {
    id: 'wrist',
    name: 'Muñecas',
    category: 'arms',
    categoryLabel: 'Tren Superior',
    isBilateral: true,
    instruction: 'Perímetro mínimo articular justo proximal a la cabeza del cúbito/radio.',
    unit: 'cm',
  },
  thigh: {
    id: 'thigh',
    name: 'Muslos (Cuádriceps)',
    category: 'legs',
    categoryLabel: 'Tren Inferior',
    isBilateral: true,
    instruction: 'Circunferencia en el punto medio superior del muslo entre cadera y rodilla.',
    unit: 'cm',
  },
  calf: {
    id: 'calf',
    name: 'Pantorrillas (Gemelos)',
    category: 'legs',
    categoryLabel: 'Tren Inferior',
    isBilateral: true,
    instruction: 'Máxima circunferencia en el vientre muscular de los gemelos de pie.',
    unit: 'cm',
  },
  ankle: {
    id: 'ankle',
    name: 'Tobillos',
    category: 'legs',
    categoryLabel: 'Tren Inferior',
    isBilateral: true,
    instruction: 'Perímetro mínimo justo por encima de los maléolos del tobillo.',
    unit: 'cm',
  },
};

export const MEASUREMENT_KEYS = [
  'pecho',
  'arm',
  'waist',
  'thigh',
  'back',
  'forearm',
  'hips',
  'calf',
  'neck',
  'wrist',
  'ankle',
  'weight',
  'height',
  'age',
  'bodyFat',
];
